# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Kumaresan\Dev\Python\lra\trunk\uis\prototype1.ui'
#
# Created: Sun Dec 11 12:23:22 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(558, 587)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks|QtGui.QMainWindow.VerticalTabs)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_12.setMargin(2)
        self.gridLayout_12.setSpacing(2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.frame_8 = QtGui.QFrame(self.groupBox)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_11.setMargin(2)
        self.gridLayout_11.setSpacing(2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.frame_5 = QtGui.QFrame(self.frame_8)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_8.setMargin(2)
        self.gridLayout_8.setSpacing(2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.toolButton_4 = QtGui.QToolButton(self.frame_5)
        self.toolButton_4.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0416/icons/04/16/01.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon)
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.gridLayout_8.addWidget(self.toolButton_4, 0, 0, 1, 1)
        self.toolButton_5 = QtGui.QToolButton(self.frame_5)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0416/icons/04/16/02.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon1)
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.gridLayout_8.addWidget(self.toolButton_5, 0, 2, 1, 1)
        self.toolButton_6 = QtGui.QToolButton(self.frame_5)
        self.toolButton_6.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0416/icons/04/16/06.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon2)
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.gridLayout_8.addWidget(self.toolButton_6, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_6 = QtGui.QFrame(self.frame_8)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_10.setMargin(2)
        self.gridLayout_10.setSpacing(2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_6, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 1, 1, 1, 1)
        self.gridLayout_12.addWidget(self.frame_8, 0, 0, 1, 1)
        self.frame_7 = QtGui.QFrame(self.groupBox)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_9.setSpacing(2)
        self.gridLayout_9.setContentsMargins(2, 2, -1, 2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_2 = QtGui.QLabel(self.frame_7)
        self.label_2.setMinimumSize(QtCore.QSize(0, 50))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_7, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setFloating(False)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setMargin(2)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.toolButton_2 = QtGui.QToolButton(self.frame)
        self.toolButton_2.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0316/icons/03/16/41.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon3)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout_3.addWidget(self.toolButton_2, 0, 5, 1, 1)
        self.toolButton = QtGui.QToolButton(self.frame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0316/icons/03/16/31.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon4)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout_3.addWidget(self.toolButton, 0, 4, 1, 1)
        self.toolButton_8 = QtGui.QToolButton(self.frame)
        self.toolButton_8.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0316/icons/03/16/42.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon5)
        self.toolButton_8.setAutoRaise(True)
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.gridLayout_3.addWidget(self.toolButton_8, 0, 6, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(194, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 10, 1, 1)
        self.toolButton_3 = QtGui.QToolButton(self.frame)
        self.toolButton_3.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0316/icons/03/16/30.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon6)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.gridLayout_3.addWidget(self.toolButton_3, 0, 12, 1, 1)
        self.toolButton_7 = QtGui.QToolButton(self.frame)
        self.toolButton_7.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0316/icons/03/16/29.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon7)
        self.toolButton_7.setAutoRaise(True)
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.gridLayout_3.addWidget(self.toolButton_7, 0, 11, 1, 1)
        self.toolButton_9 = QtGui.QToolButton(self.frame)
        self.toolButton_9.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0116/icons/01/16/46.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setIcon(icon8)
        self.toolButton_9.setAutoRaise(True)
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.gridLayout_3.addWidget(self.toolButton_9, 0, 16, 1, 1)
        self.toolButton_10 = QtGui.QToolButton(self.frame)
        self.toolButton_10.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0216/icons/02/16/45.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_10.setIcon(icon9)
        self.toolButton_10.setAutoRaise(True)
        self.toolButton_10.setObjectName(_fromUtf8("toolButton_10"))
        self.gridLayout_3.addWidget(self.toolButton_10, 0, 15, 1, 1)
        self.line = QtGui.QFrame(self.frame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 0, 13, 1, 1)
        self.toolButton_11 = QtGui.QToolButton(self.frame)
        self.toolButton_11.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0116/icons/01/16/21.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_11.setIcon(icon10)
        self.toolButton_11.setAutoRaise(True)
        self.toolButton_11.setObjectName(_fromUtf8("toolButton_11"))
        self.gridLayout_3.addWidget(self.toolButton_11, 0, 14, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.dockWidgetContents)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.frame_2)
        self.tableWidget.setFrameShape(QtGui.QFrame.Box)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon4)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0216/icons/02/16/37.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon11)
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0316/icons/03/16/02.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon12)
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon11)
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon12)
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setIcon(icon11)
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_7.setMargin(2)
        self.gridLayout_7.setSpacing(2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame_3 = QtGui.QFrame(self.dockWidgetContents_2)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_5.setMargin(2)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 1, 1, 1)
        self.toolButton_12 = QtGui.QToolButton(self.frame_3)
        self.toolButton_12.setEnabled(False)
        self.toolButton_12.setIcon(icon8)
        self.toolButton_12.setAutoRaise(True)
        self.toolButton_12.setObjectName(_fromUtf8("toolButton_12"))
        self.gridLayout_5.addWidget(self.toolButton_12, 0, 4, 1, 1)
        self.toolButton_13 = QtGui.QToolButton(self.frame_3)
        self.toolButton_13.setEnabled(False)
        self.toolButton_13.setIcon(icon10)
        self.toolButton_13.setAutoRaise(True)
        self.toolButton_13.setObjectName(_fromUtf8("toolButton_13"))
        self.gridLayout_5.addWidget(self.toolButton_13, 0, 3, 1, 1)
        self.toolButton_14 = QtGui.QToolButton(self.frame_3)
        self.toolButton_14.setEnabled(False)
        self.toolButton_14.setIcon(icon9)
        self.toolButton_14.setAutoRaise(True)
        self.toolButton_14.setObjectName(_fromUtf8("toolButton_14"))
        self.gridLayout_5.addWidget(self.toolButton_14, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.dockWidgetContents_2)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_6.setMargin(2)
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.textBrowser = QtGui.QTextBrowser(self.frame_4)
        self.textBrowser.setFrameShape(QtGui.QFrame.Panel)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_6.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_4, 1, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_2)
        self.actionSave_list = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0216/icons/02/16/46.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_list.setIcon(icon13)
        self.actionSave_list.setObjectName(_fromUtf8("actionSave_list"))
        self.actionLoad_list = QtGui.QAction(MainWindow)
        self.actionLoad_list.setIcon(icon8)
        self.actionLoad_list.setObjectName(_fromUtf8("actionLoad_list"))
        self.actionNew_list = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/ic0116/icons/01/16/22.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_list.setIcon(icon14)
        self.actionNew_list.setObjectName(_fromUtf8("actionNew_list"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.actionSelect_None = QtGui.QAction(MainWindow)
        self.actionSelect_None.setObjectName(_fromUtf8("actionSelect_None"))
        self.actionAbout_lra = QtGui.QAction(MainWindow)
        self.actionAbout_lra.setObjectName(_fromUtf8("actionAbout_lra"))
        self.actionAbout_PyQt = QtGui.QAction(MainWindow)
        self.actionAbout_PyQt.setObjectName(_fromUtf8("actionAbout_PyQt"))
        self.actionAbout_Python = QtGui.QAction(MainWindow)
        self.actionAbout_Python.setObjectName(_fromUtf8("actionAbout_Python"))
        self.menuFile.addAction(self.actionNew_list)
        self.menuFile.addAction(self.actionSave_list)
        self.menuFile.addAction(self.actionLoad_list)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionSelect_None)
        self.menuAbout.addAction(self.actionAbout_lra)
        self.menuAbout.addAction(self.actionAbout_PyQt)
        self.menuAbout.addAction(self.actionAbout_Python)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "lra", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_6.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Rendering!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">ABCD_XYZ_KLMN_OPQR_1234_5678_A_B_C_D1_D2_D3.mb</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Render List", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_8.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_7.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_9.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_10.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_11.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "New Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "FileName", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "StartFrame", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "EndFrame", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "ProjPath", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 1).setText(QtGui.QApplication.translate("MainWindow", "ABCD_XYZ_KLMN_OPQR_1234_5678_A_B_C_D1_D2_D3.mb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 2).setText(QtGui.QApplication.translate("MainWindow", "3434", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 3).setText(QtGui.QApplication.translate("MainWindow", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "Waiting", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 1).setText(QtGui.QApplication.translate("MainWindow", "ABCD_XYZ_KLMN_OPQR_1234_5678_A_B_C_D1_D2_D3.mb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 2).setText(QtGui.QApplication.translate("MainWindow", "54", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 3).setText(QtGui.QApplication.translate("MainWindow", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 1).setText(QtGui.QApplication.translate("MainWindow", "ABCD_XYZ_KLMN_OPQR_1234_5678_A_B_C_D1_D2_D3.mb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 2).setText(QtGui.QApplication.translate("MainWindow", "234", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 3).setText(QtGui.QApplication.translate("MainWindow", "454", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(3, 0).setText(QtGui.QApplication.translate("MainWindow", "Waiting", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(3, 1).setText(QtGui.QApplication.translate("MainWindow", "ABCD_XYZ_KLMN_OPQR_1234_5678_A_B_C_D1_D2_D3.mb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(3, 2).setText(QtGui.QApplication.translate("MainWindow", "5454", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(3, 3).setText(QtGui.QApplication.translate("MainWindow", "545", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(4, 0).setText(QtGui.QApplication.translate("MainWindow", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(4, 1).setText(QtGui.QApplication.translate("MainWindow", "ABCD_XYZ_KLMN_OPQR_1234_5678_A_B_C_D1_D2_D3.mb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(4, 2).setText(QtGui.QApplication.translate("MainWindow", "34", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(4, 3).setText(QtGui.QApplication.translate("MainWindow", "454545", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(5, 0).setText(QtGui.QApplication.translate("MainWindow", "Waiting", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(5, 1).setText(QtGui.QApplication.translate("MainWindow", "ABCD_XYZ_KLMN_OPQR_1234_5678_A_B_C_D1_D2_D3.mb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(5, 2).setText(QtGui.QApplication.translate("MainWindow", "5454", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(5, 3).setText(QtGui.QApplication.translate("MainWindow", "54", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_12.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_13.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_14.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Started Rendering...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">ABCD_XYZ_KLMN_OPQR_1234_5678_A_B_C_D1_D2_D3.mb</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Warning!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">abc texture missing...!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Warning!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">zxczxc abc texture missing...!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Warning!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">zczxczxcabc texture missing...!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_list.setText(QtGui.QApplication.translate("MainWindow", "Save list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_list.setText(QtGui.QApplication.translate("MainWindow", "Load list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_list.setText(QtGui.QApplication.translate("MainWindow", "New list", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_All.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_None.setText(QtGui.QApplication.translate("MainWindow", "Select None", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_lra.setText(QtGui.QApplication.translate("MainWindow", "About lra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_PyQt.setText(QtGui.QApplication.translate("MainWindow", "About PyQt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Python.setText(QtGui.QApplication.translate("MainWindow", "About Python", None, QtGui.QApplication.UnicodeUTF8))

import imgs_rc
