# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Kumaresan\Dev\Python\lra\uis\winMain.ui'
#
# Created: Thu Jan 12 09:41:32 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1083, 916)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_16 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_16.setMargin(2)
        self.gridLayout_16.setSpacing(2)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_7.setMargin(1)
        self.gridLayout_7.setSpacing(1)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame_4 = QtGui.QFrame(self.groupBox)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_8.setMargin(1)
        self.gridLayout_8.setSpacing(1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem = QtGui.QSpacerItem(272, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 1, 1, 1)
        self.lblStatus = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Trebuchet MS"))
        font.setPointSize(10)
        self.lblStatus.setFont(font)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.gridLayout_8.addWidget(self.lblStatus, 0, 0, 1, 1)
        self.btnLogSave = QtGui.QToolButton(self.frame_4)
        self.btnLogSave.setAutoRaise(True)
        self.btnLogSave.setObjectName(_fromUtf8("btnLogSave"))
        self.gridLayout_8.addWidget(self.btnLogSave, 0, 3, 1, 1)
        self.btnLogClear = QtGui.QToolButton(self.frame_4)
        self.btnLogClear.setAutoRaise(True)
        self.btnLogClear.setObjectName(_fromUtf8("btnLogClear"))
        self.gridLayout_8.addWidget(self.btnLogClear, 0, 2, 1, 1)
        self.btnSearchAppLog = QtGui.QToolButton(self.frame_4)
        self.btnSearchAppLog.setAutoRaise(True)
        self.btnSearchAppLog.setObjectName(_fromUtf8("btnSearchAppLog"))
        self.gridLayout_8.addWidget(self.btnSearchAppLog, 0, 5, 1, 1)
        self.leSearchAppLog = QtGui.QLineEdit(self.frame_4)
        self.leSearchAppLog.setMinimumSize(QtCore.QSize(200, 0))
        self.leSearchAppLog.setObjectName(_fromUtf8("leSearchAppLog"))
        self.gridLayout_8.addWidget(self.leSearchAppLog, 0, 4, 1, 1)
        self.gridLayout_7.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.groupBox)
        self.frame_5.setFrameShape(QtGui.QFrame.Panel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_12.setMargin(1)
        self.gridLayout_12.setSpacing(1)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.tbStatus = QtGui.QTextBrowser(self.frame_5)
        self.tbStatus.setFrameShape(QtGui.QFrame.NoFrame)
        self.tbStatus.setObjectName(_fromUtf8("tbStatus"))
        self.gridLayout_12.addWidget(self.tbStatus, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 1, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dckRenderTasks = QtGui.QDockWidget(MainWindow)
        self.dckRenderTasks.setObjectName(_fromUtf8("dckRenderTasks"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame_2 = QtGui.QFrame(self.dockWidgetContents)
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_3.setMargin(1)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblMainList = QtGui.QTableWidget(self.frame_2)
        self.tblMainList.setFrameShape(QtGui.QFrame.Panel)
        self.tblMainList.setAlternatingRowColors(True)
        self.tblMainList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblMainList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblMainList.setObjectName(_fromUtf8("tblMainList"))
        self.tblMainList.setColumnCount(0)
        self.tblMainList.setRowCount(0)
        self.gridLayout_3.addWidget(self.tblMainList, 1, 1, 12, 1)
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(0, 30))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnStartRender = QtGui.QToolButton(self.frame)
        self.btnStartRender.setAutoRaise(True)
        self.btnStartRender.setObjectName(_fromUtf8("btnStartRender"))
        self.gridLayout_2.addWidget(self.btnStartRender, 0, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 9, 1, 1)
        self.btnTerminate = QtGui.QToolButton(self.frame)
        self.btnTerminate.setAutoRaise(True)
        self.btnTerminate.setObjectName(_fromUtf8("btnTerminate"))
        self.gridLayout_2.addWidget(self.btnTerminate, 0, 8, 1, 1)
        self.btnSkipRender = QtGui.QToolButton(self.frame)
        self.btnSkipRender.setAutoRaise(True)
        self.btnSkipRender.setObjectName(_fromUtf8("btnSkipRender"))
        self.gridLayout_2.addWidget(self.btnSkipRender, 0, 7, 1, 1)
        self.line = QtGui.QFrame(self.frame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 0, 5, 1, 1)
        self.btnRTaskSave = QtGui.QToolButton(self.frame)
        self.btnRTaskSave.setAutoRaise(True)
        self.btnRTaskSave.setObjectName(_fromUtf8("btnRTaskSave"))
        self.gridLayout_2.addWidget(self.btnRTaskSave, 0, 4, 1, 1)
        self.btnRTaskLoad = QtGui.QToolButton(self.frame)
        self.btnRTaskLoad.setAutoRaise(True)
        self.btnRTaskLoad.setObjectName(_fromUtf8("btnRTaskLoad"))
        self.gridLayout_2.addWidget(self.btnRTaskLoad, 0, 3, 1, 1)
        self.btnSearchRenderTask = QtGui.QToolButton(self.frame)
        self.btnSearchRenderTask.setAutoRaise(True)
        self.btnSearchRenderTask.setObjectName(_fromUtf8("btnSearchRenderTask"))
        self.gridLayout_2.addWidget(self.btnSearchRenderTask, 0, 11, 1, 1)
        self.leSearchRenderTask = QtGui.QLineEdit(self.frame)
        self.leSearchRenderTask.setObjectName(_fromUtf8("leSearchRenderTask"))
        self.gridLayout_2.addWidget(self.leSearchRenderTask, 0, 10, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 2)
        self.btnAddFile = QtGui.QToolButton(self.frame_2)
        self.btnAddFile.setAutoRaise(True)
        self.btnAddFile.setObjectName(_fromUtf8("btnAddFile"))
        self.gridLayout_3.addWidget(self.btnAddFile, 2, 0, 1, 1)
        self.btnRemoveFile = QtGui.QToolButton(self.frame_2)
        self.btnRemoveFile.setAutoRaise(True)
        self.btnRemoveFile.setObjectName(_fromUtf8("btnRemoveFile"))
        self.gridLayout_3.addWidget(self.btnRemoveFile, 5, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 6, 0, 1, 1)
        self.btnMoveUp = QtGui.QToolButton(self.frame_2)
        self.btnMoveUp.setAutoRaise(True)
        self.btnMoveUp.setObjectName(_fromUtf8("btnMoveUp"))
        self.gridLayout_3.addWidget(self.btnMoveUp, 8, 0, 1, 1)
        self.btnMoveDown = QtGui.QToolButton(self.frame_2)
        self.btnMoveDown.setAutoRaise(True)
        self.btnMoveDown.setObjectName(_fromUtf8("btnMoveDown"))
        self.gridLayout_3.addWidget(self.btnMoveDown, 9, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 11, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.frame_2)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_3.addWidget(self.line_5, 1, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.frame_2)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_3.addWidget(self.line_6, 10, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.dckRenderTasks.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dckRenderTasks)
        self.dckProperties = QtGui.QDockWidget(MainWindow)
        self.dckProperties.setObjectName(_fromUtf8("dckProperties"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents_2)
        self.scrollArea.setFrameShape(QtGui.QFrame.Panel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 568, 774))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_6 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.frame_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_13.setMargin(1)
        self.gridLayout_13.setHorizontalSpacing(1)
        self.gridLayout_13.setVerticalSpacing(5)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.frmPropFileInfo = QtGui.QGroupBox(self.frame_3)
        self.frmPropFileInfo.setFlat(True)
        self.frmPropFileInfo.setObjectName(_fromUtf8("frmPropFileInfo"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frmPropFileInfo)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_5 = QtGui.QLabel(self.frmPropFileInfo)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_10.addWidget(self.label_5, 0, 0, 1, 1)
        self.lePropFileName = QtGui.QLineEdit(self.frmPropFileInfo)
        self.lePropFileName.setReadOnly(True)
        self.lePropFileName.setObjectName(_fromUtf8("lePropFileName"))
        self.gridLayout_10.addWidget(self.lePropFileName, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frmPropFileInfo)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_10.addWidget(self.label_6, 1, 0, 1, 1)
        self.lePropFilePath = QtGui.QLineEdit(self.frmPropFileInfo)
        self.lePropFilePath.setReadOnly(True)
        self.lePropFilePath.setObjectName(_fromUtf8("lePropFilePath"))
        self.gridLayout_10.addWidget(self.lePropFilePath, 1, 1, 1, 1)
        self.gridLayout_13.addWidget(self.frmPropFileInfo, 0, 0, 1, 1)
        self.frmPropProjPath = QtGui.QGroupBox(self.frame_3)
        self.frmPropProjPath.setFlat(True)
        self.frmPropProjPath.setCheckable(True)
        self.frmPropProjPath.setChecked(False)
        self.frmPropProjPath.setObjectName(_fromUtf8("frmPropProjPath"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frmPropProjPath)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.lePropProjPath = QtGui.QLineEdit(self.frmPropProjPath)
        self.lePropProjPath.setText(_fromUtf8(""))
        self.lePropProjPath.setObjectName(_fromUtf8("lePropProjPath"))
        self.gridLayout_11.addWidget(self.lePropProjPath, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frmPropProjPath, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem3, 9, 0, 1, 1)
        self.frmPropRDPath = QtGui.QGroupBox(self.frame_3)
        self.frmPropRDPath.setFlat(True)
        self.frmPropRDPath.setCheckable(True)
        self.frmPropRDPath.setChecked(False)
        self.frmPropRDPath.setObjectName(_fromUtf8("frmPropRDPath"))
        self.gridLayout_17 = QtGui.QGridLayout(self.frmPropRDPath)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.lePropRDPath = QtGui.QLineEdit(self.frmPropRDPath)
        self.lePropRDPath.setText(_fromUtf8(""))
        self.lePropRDPath.setObjectName(_fromUtf8("lePropRDPath"))
        self.gridLayout_17.addWidget(self.lePropRDPath, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frmPropRDPath, 3, 0, 1, 1)
        self.frmPropOutputFormat = QtGui.QGroupBox(self.frame_3)
        self.frmPropOutputFormat.setFlat(True)
        self.frmPropOutputFormat.setCheckable(True)
        self.frmPropOutputFormat.setChecked(False)
        self.frmPropOutputFormat.setObjectName(_fromUtf8("frmPropOutputFormat"))
        self.gridLayout_18 = QtGui.QGridLayout(self.frmPropOutputFormat)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.lePropOFPath = QtGui.QLineEdit(self.frmPropOutputFormat)
        self.lePropOFPath.setText(_fromUtf8(""))
        self.lePropOFPath.setObjectName(_fromUtf8("lePropOFPath"))
        self.gridLayout_18.addWidget(self.lePropOFPath, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frmPropOutputFormat, 4, 0, 1, 1)
        self.frmPropCam = QtGui.QGroupBox(self.frame_3)
        self.frmPropCam.setFlat(True)
        self.frmPropCam.setCheckable(True)
        self.frmPropCam.setChecked(False)
        self.frmPropCam.setObjectName(_fromUtf8("frmPropCam"))
        self.gridLayout_19 = QtGui.QGridLayout(self.frmPropCam)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.lePropCamName = QtGui.QLineEdit(self.frmPropCam)
        self.lePropCamName.setText(_fromUtf8(""))
        self.lePropCamName.setObjectName(_fromUtf8("lePropCamName"))
        self.gridLayout_19.addWidget(self.lePropCamName, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.frmPropCam)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_19.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.frmPropCam)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_19.addWidget(self.label_9, 1, 0, 1, 1)
        self.lePropCamRGB = QtGui.QLineEdit(self.frmPropCam)
        self.lePropCamRGB.setText(_fromUtf8(""))
        self.lePropCamRGB.setObjectName(_fromUtf8("lePropCamRGB"))
        self.gridLayout_19.addWidget(self.lePropCamRGB, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.frmPropCam)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_19.addWidget(self.label_10, 2, 0, 1, 1)
        self.lePropCamAlpha = QtGui.QLineEdit(self.frmPropCam)
        self.lePropCamAlpha.setText(_fromUtf8(""))
        self.lePropCamAlpha.setObjectName(_fromUtf8("lePropCamAlpha"))
        self.gridLayout_19.addWidget(self.lePropCamAlpha, 2, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.frmPropCam)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_19.addWidget(self.label_11, 3, 0, 1, 1)
        self.lePropCamDepth = QtGui.QLineEdit(self.frmPropCam)
        self.lePropCamDepth.setText(_fromUtf8(""))
        self.lePropCamDepth.setObjectName(_fromUtf8("lePropCamDepth"))
        self.gridLayout_19.addWidget(self.lePropCamDepth, 3, 2, 1, 1)
        self.gridLayout_13.addWidget(self.frmPropCam, 5, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.frmPropResAbs = QtGui.QGroupBox(self.groupBox_2)
        self.frmPropResAbs.setFlat(True)
        self.frmPropResAbs.setCheckable(True)
        self.frmPropResAbs.setChecked(False)
        self.frmPropResAbs.setObjectName(_fromUtf8("frmPropResAbs"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frmPropResAbs)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.lePropYRes = QtGui.QLineEdit(self.frmPropResAbs)
        self.lePropYRes.setText(_fromUtf8(""))
        self.lePropYRes.setObjectName(_fromUtf8("lePropYRes"))
        self.gridLayout_20.addWidget(self.lePropYRes, 1, 1, 1, 1)
        self.lePropXRes = QtGui.QLineEdit(self.frmPropResAbs)
        self.lePropXRes.setText(_fromUtf8(""))
        self.lePropXRes.setObjectName(_fromUtf8("lePropXRes"))
        self.gridLayout_20.addWidget(self.lePropXRes, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.frmPropResAbs)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_20.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.frmPropResAbs)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_20.addWidget(self.label_13, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frmPropResAbs, 0, 0, 1, 1)
        self.frmPropResPercentage = QtGui.QGroupBox(self.groupBox_2)
        self.frmPropResPercentage.setFlat(True)
        self.frmPropResPercentage.setCheckable(True)
        self.frmPropResPercentage.setChecked(False)
        self.frmPropResPercentage.setObjectName(_fromUtf8("frmPropResPercentage"))
        self.gridLayout_21 = QtGui.QGridLayout(self.frmPropResPercentage)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.lePropPercRes = QtGui.QLineEdit(self.frmPropResPercentage)
        self.lePropPercRes.setText(_fromUtf8(""))
        self.lePropPercRes.setObjectName(_fromUtf8("lePropPercRes"))
        self.gridLayout_21.addWidget(self.lePropPercRes, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.frmPropResPercentage)
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_21.addWidget(self.label_14, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frmPropResPercentage, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_2, 6, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.frame_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_22 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.frmPropFrameRange = QtGui.QGroupBox(self.groupBox_3)
        self.frmPropFrameRange.setFlat(True)
        self.frmPropFrameRange.setCheckable(True)
        self.frmPropFrameRange.setChecked(False)
        self.frmPropFrameRange.setObjectName(_fromUtf8("frmPropFrameRange"))
        self.gridLayout_23 = QtGui.QGridLayout(self.frmPropFrameRange)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.label_15 = QtGui.QLabel(self.frmPropFrameRange)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_23.addWidget(self.label_15, 0, 0, 1, 1)
        self.lePropStartFrame = QtGui.QLineEdit(self.frmPropFrameRange)
        self.lePropStartFrame.setText(_fromUtf8(""))
        self.lePropStartFrame.setObjectName(_fromUtf8("lePropStartFrame"))
        self.gridLayout_23.addWidget(self.lePropStartFrame, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.frmPropFrameRange)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_23.addWidget(self.label_16, 1, 0, 1, 1)
        self.lePropEndFrame = QtGui.QLineEdit(self.frmPropFrameRange)
        self.lePropEndFrame.setText(_fromUtf8(""))
        self.lePropEndFrame.setObjectName(_fromUtf8("lePropEndFrame"))
        self.gridLayout_23.addWidget(self.lePropEndFrame, 1, 1, 1, 1)
        self.gridLayout_22.addWidget(self.frmPropFrameRange, 0, 0, 1, 1)
        self.frmPropFrameAttribs = QtGui.QGroupBox(self.groupBox_3)
        self.frmPropFrameAttribs.setFlat(True)
        self.frmPropFrameAttribs.setCheckable(True)
        self.frmPropFrameAttribs.setChecked(False)
        self.frmPropFrameAttribs.setObjectName(_fromUtf8("frmPropFrameAttribs"))
        self.gridLayout_24 = QtGui.QGridLayout(self.frmPropFrameAttribs)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.lePropByFrame = QtGui.QLineEdit(self.frmPropFrameAttribs)
        self.lePropByFrame.setText(_fromUtf8(""))
        self.lePropByFrame.setObjectName(_fromUtf8("lePropByFrame"))
        self.gridLayout_24.addWidget(self.lePropByFrame, 0, 1, 1, 1)
        self.lePropPadding = QtGui.QLineEdit(self.frmPropFrameAttribs)
        self.lePropPadding.setText(_fromUtf8(""))
        self.lePropPadding.setObjectName(_fromUtf8("lePropPadding"))
        self.gridLayout_24.addWidget(self.lePropPadding, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.frmPropFrameAttribs)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_24.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.frmPropFrameAttribs)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_24.addWidget(self.label_21, 1, 0, 1, 1)
        self.gridLayout_22.addWidget(self.frmPropFrameAttribs, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.frmPropRenderLayer = QtGui.QGroupBox(self.frame_3)
        self.frmPropRenderLayer.setFlat(True)
        self.frmPropRenderLayer.setCheckable(True)
        self.frmPropRenderLayer.setChecked(False)
        self.frmPropRenderLayer.setObjectName(_fromUtf8("frmPropRenderLayer"))
        self.gridLayout_25 = QtGui.QGridLayout(self.frmPropRenderLayer)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.lePropRenderLayer = QtGui.QLineEdit(self.frmPropRenderLayer)
        self.lePropRenderLayer.setText(_fromUtf8(""))
        self.lePropRenderLayer.setObjectName(_fromUtf8("lePropRenderLayer"))
        self.gridLayout_25.addWidget(self.lePropRenderLayer, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frmPropRenderLayer, 7, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frmPropCustoms = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.frmPropCustoms.setFlat(True)
        self.frmPropCustoms.setCheckable(True)
        self.frmPropCustoms.setChecked(False)
        self.frmPropCustoms.setObjectName(_fromUtf8("frmPropCustoms"))
        self.gridLayout_26 = QtGui.QGridLayout(self.frmPropCustoms)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.lePropCustoms = QtGui.QLineEdit(self.frmPropCustoms)
        self.lePropCustoms.setText(_fromUtf8(""))
        self.lePropCustoms.setObjectName(_fromUtf8("lePropCustoms"))
        self.gridLayout_26.addWidget(self.lePropCustoms, 0, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.frmPropCustoms)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_26.addWidget(self.label_17, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frmPropCustoms, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.frmPropButtons = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.frmPropButtons.setTitle(_fromUtf8(""))
        self.frmPropButtons.setFlat(True)
        self.frmPropButtons.setObjectName(_fromUtf8("frmPropButtons"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frmPropButtons)
        self.gridLayout_14.setMargin(2)
        self.gridLayout_14.setSpacing(2)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem4, 0, 0, 1, 1)
        self.btnPropApply = QtGui.QToolButton(self.frmPropButtons)
        self.btnPropApply.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnPropApply.setAutoRaise(True)
        self.btnPropApply.setObjectName(_fromUtf8("btnPropApply"))
        self.gridLayout_14.addWidget(self.btnPropApply, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frmPropButtons, 1, 0, 1, 1)
        self.dckProperties.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dckProperties)
        self.dckColumns = QtGui.QDockWidget(MainWindow)
        self.dckColumns.setObjectName(_fromUtf8("dckColumns"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_15 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.lstColumns = QtGui.QListWidget(self.dockWidgetContents_3)
        self.lstColumns.setFrameShape(QtGui.QFrame.Panel)
        self.lstColumns.setAlternatingRowColors(True)
        self.lstColumns.setObjectName(_fromUtf8("lstColumns"))
        self.gridLayout_15.addWidget(self.lstColumns, 0, 0, 1, 1)
        self.dckColumns.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dckColumns)
        self.tbrDcks = QtGui.QToolBar(MainWindow)
        self.tbrDcks.setIconSize(QtCore.QSize(18, 18))
        self.tbrDcks.setObjectName(_fromUtf8("tbrDcks"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tbrDcks)
        self.dckLog = QtGui.QDockWidget(MainWindow)
        self.dckLog.setObjectName(_fromUtf8("dckLog"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cbxAutoScroll = QtGui.QCheckBox(self.dockWidgetContents_4)
        self.cbxAutoScroll.setEnabled(False)
        self.cbxAutoScroll.setChecked(True)
        self.cbxAutoScroll.setObjectName(_fromUtf8("cbxAutoScroll"))
        self.gridLayout.addWidget(self.cbxAutoScroll, 6, 0, 1, 1)
        self.tbLog = QtGui.QPlainTextEdit(self.dockWidgetContents_4)
        self.tbLog.setReadOnly(True)
        self.tbLog.setPlainText(_fromUtf8(""))
        self.tbLog.setObjectName(_fromUtf8("tbLog"))
        self.gridLayout.addWidget(self.tbLog, 5, 0, 1, 4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 1, 1, 1)
        self.btnSearchRenderLog = QtGui.QToolButton(self.dockWidgetContents_4)
        self.btnSearchRenderLog.setAutoRaise(True)
        self.btnSearchRenderLog.setObjectName(_fromUtf8("btnSearchRenderLog"))
        self.gridLayout.addWidget(self.btnSearchRenderLog, 2, 3, 1, 1)
        self.leSearchRenderLog = QtGui.QLineEdit(self.dockWidgetContents_4)
        self.leSearchRenderLog.setObjectName(_fromUtf8("leSearchRenderLog"))
        self.gridLayout.addWidget(self.leSearchRenderLog, 2, 2, 1, 1)
        self.dckLog.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dckLog)
        self.tbrFile = QtGui.QToolBar(MainWindow)
        self.tbrFile.setObjectName(_fromUtf8("tbrFile"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tbrFile)
        self.actionRenderTasks = QtGui.QAction(MainWindow)
        self.actionRenderTasks.setCheckable(True)
        self.actionRenderTasks.setChecked(True)
        self.actionRenderTasks.setObjectName(_fromUtf8("actionRenderTasks"))
        self.actionProperties = QtGui.QAction(MainWindow)
        self.actionProperties.setCheckable(True)
        self.actionProperties.setChecked(True)
        self.actionProperties.setObjectName(_fromUtf8("actionProperties"))
        self.actionColumns = QtGui.QAction(MainWindow)
        self.actionColumns.setCheckable(True)
        self.actionColumns.setChecked(True)
        self.actionColumns.setObjectName(_fromUtf8("actionColumns"))
        self.actionLog = QtGui.QAction(MainWindow)
        self.actionLog.setCheckable(True)
        self.actionLog.setChecked(True)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionNew_List = QtGui.QAction(MainWindow)
        self.actionNew_List.setObjectName(_fromUtf8("actionNew_List"))
        self.actionLoad_List = QtGui.QAction(MainWindow)
        self.actionLoad_List.setObjectName(_fromUtf8("actionLoad_List"))
        self.actionSave_List = QtGui.QAction(MainWindow)
        self.actionSave_List.setObjectName(_fromUtf8("actionSave_List"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionAbout_lra = QtGui.QAction(MainWindow)
        self.actionAbout_lra.setObjectName(_fromUtf8("actionAbout_lra"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionTest = QtGui.QAction(MainWindow)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionReportIssues = QtGui.QAction(MainWindow)
        self.actionReportIssues.setObjectName(_fromUtf8("actionReportIssues"))
        self.actionOnline_Help = QtGui.QAction(MainWindow)
        self.actionOnline_Help.setObjectName(_fromUtf8("actionOnline_Help"))
        self.actionConsole = QtGui.QAction(MainWindow)
        self.actionConsole.setObjectName(_fromUtf8("actionConsole"))
        self.menuFile.addAction(self.actionNew_List)
        self.menuFile.addAction(self.actionLoad_List)
        self.menuFile.addAction(self.actionSave_List)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuTools.addAction(self.actionSettings)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionConsole)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionOnline_Help)
        self.menuAbout.addAction(self.actionReportIssues)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout_lra)
        self.menuView.addAction(self.actionRenderTasks)
        self.menuView.addAction(self.actionProperties)
        self.menuView.addAction(self.actionColumns)
        self.menuView.addAction(self.actionLog)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.tbrDcks.addAction(self.actionRenderTasks)
        self.tbrDcks.addAction(self.actionProperties)
        self.tbrDcks.addAction(self.actionColumns)
        self.tbrDcks.addAction(self.actionLog)
        self.tbrFile.addAction(self.actionNew_List)
        self.tbrFile.addAction(self.actionLoad_List)
        self.tbrFile.addAction(self.actionSave_List)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setText(QtGui.QApplication.translate("MainWindow", "Application Log: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLogSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLogSave.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLogSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLogClear.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLogClear.setStatusTip(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLogClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearchAppLog.setToolTip(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearchAppLog.setStatusTip(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearchAppLog.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.dckRenderTasks.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Render Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.tblMainList.setSortingEnabled(True)
        self.btnStartRender.setToolTip(QtGui.QApplication.translate("MainWindow", "Start Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStartRender.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStartRender.setText(QtGui.QApplication.translate("MainWindow", "Start Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTerminate.setToolTip(QtGui.QApplication.translate("MainWindow", "Stop Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTerminate.setStatusTip(QtGui.QApplication.translate("MainWindow", "Stop Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTerminate.setText(QtGui.QApplication.translate("MainWindow", "Stop Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSkipRender.setToolTip(QtGui.QApplication.translate("MainWindow", "Skip Current Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSkipRender.setStatusTip(QtGui.QApplication.translate("MainWindow", "Skip Current Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSkipRender.setText(QtGui.QApplication.translate("MainWindow", "Skip Current Rendering", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRTaskSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRTaskSave.setStatusTip(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRTaskSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRTaskLoad.setToolTip(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRTaskLoad.setStatusTip(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRTaskLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearchRenderTask.setToolTip(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearchRenderTask.setStatusTip(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearchRenderTask.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddFile.setToolTip(QtGui.QApplication.translate("MainWindow", "Add File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddFile.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddFile.setText(QtGui.QApplication.translate("MainWindow", "Add File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveFile.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveFile.setStatusTip(QtGui.QApplication.translate("MainWindow", "Remove File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemoveFile.setText(QtGui.QApplication.translate("MainWindow", "Remove File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMoveUp.setToolTip(QtGui.QApplication.translate("MainWindow", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMoveUp.setStatusTip(QtGui.QApplication.translate("MainWindow", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMoveUp.setText(QtGui.QApplication.translate("MainWindow", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMoveDown.setToolTip(QtGui.QApplication.translate("MainWindow", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMoveDown.setStatusTip(QtGui.QApplication.translate("MainWindow", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMoveDown.setText(QtGui.QApplication.translate("MainWindow", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
        self.dckProperties.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropFileInfo.setTitle(QtGui.QApplication.translate("MainWindow", "File Info:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropProjPath.setTitle(QtGui.QApplication.translate("MainWindow", "Proj Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropProjPath.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Project Path", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropProjPath.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "proj", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropRDPath.setTitle(QtGui.QApplication.translate("MainWindow", "Render Desitination Path (RD):", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropRDPath.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Render Path", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropRDPath.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "rd", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropOutputFormat.setTitle(QtGui.QApplication.translate("MainWindow", "Output Format (OF):", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropOFPath.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Output Image Format", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropOFPath.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "of", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropCam.setTitle(QtGui.QApplication.translate("MainWindow", "Cameras:", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropCamName.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropCamName.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "cam", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "RGB ON/OFF: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropCamRGB.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "RGB", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropCamRGB.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "rgb", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "ALPHA ON/OFF: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropCamAlpha.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropCamAlpha.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "DEPTH ON/OFF: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropCamDepth.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropCamDepth.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "depth", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropResAbs.setTitle(QtGui.QApplication.translate("MainWindow", "Absolute", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropYRes.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Resolution Y", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropYRes.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropXRes.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Resolution X", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropXRes.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "XRes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "YRes:", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropResPercentage.setTitle(QtGui.QApplication.translate("MainWindow", "Percentage", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropPercRes.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Res Percent", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropPercRes.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "percentRes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Frames:", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropFrameRange.setTitle(QtGui.QApplication.translate("MainWindow", "Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Start Frame:", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropStartFrame.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Start Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropStartFrame.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "End Frame:", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropEndFrame.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "End Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropEndFrame.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "e", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropFrameAttribs.setTitle(QtGui.QApplication.translate("MainWindow", "Frame Attribs:", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropByFrame.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "ByFrame", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropByFrame.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "b", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropPadding.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Padding", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropPadding.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "pad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "By Frame:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Padding:", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropRenderLayer.setTitle(QtGui.QApplication.translate("MainWindow", "Render Layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropRenderLayer.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Render Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropRenderLayer.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "l", None, QtGui.QApplication.UnicodeUTF8))
        self.frmPropCustoms.setTitle(QtGui.QApplication.translate("MainWindow", "Custom Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropCustoms.setProperty(_fromUtf8("flagFullName"), QtGui.QApplication.translate("MainWindow", "Render Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.lePropCustoms.setProperty(_fromUtf8("flagShortName"), QtGui.QApplication.translate("MainWindow", "l", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Eg: -mr:w  \"DFILE\" -preRenderMel \"special.mel\"", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPropApply.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.dckColumns.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Customize Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.tbrDcks.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Dock Tool Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.dckLog.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Render Log", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAutoScroll.setText(QtGui.QApplication.translate("MainWindow", "AutoScroll", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearchRenderLog.setToolTip(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearchRenderLog.setStatusTip(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearchRenderLog.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tbrFile.setWindowTitle(QtGui.QApplication.translate("MainWindow", "File Tool Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRenderTasks.setText(QtGui.QApplication.translate("MainWindow", "Render Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProperties.setText(QtGui.QApplication.translate("MainWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.actionColumns.setText(QtGui.QApplication.translate("MainWindow", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog.setText(QtGui.QApplication.translate("MainWindow", "Render Log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_List.setText(QtGui.QApplication.translate("MainWindow", "New List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_List.setText(QtGui.QApplication.translate("MainWindow", "Load List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_List.setText(QtGui.QApplication.translate("MainWindow", "Save List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_lra.setText(QtGui.QApplication.translate("MainWindow", "About lra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("MainWindow", "test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReportIssues.setText(QtGui.QApplication.translate("MainWindow", "Report Issues", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOnline_Help.setText(QtGui.QApplication.translate("MainWindow", "Online Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConsole.setText(QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))

